enable:
	sudo systemctl enable nginx

start:
	sudo systemctl start nginx

restart:
	sudo systemctl restart nginx

stop:
	sudo systemctl stop nginx

reload:
	sudo systemctl reload nginx

status:
	sudo systemctl status nginx